name: Generate ASCII Artwork

on: push

jobs:
  shali_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v4

    - name: List files
      run: ls -ltra
    
    - name: Executing Shell Scripts
      run: ./ascii-script.sh
      