name: My CICD workflow

on: push

jobs:
  shali_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v4

    - name: Testing Message
      run: |
        echo "Testing Pipeline action"
        ls -ltra
        cat README.md

    - name: Generate ASCII Artwork
      run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt


    # - name: List files
    #   run: ls

    # - name: Read file
    #   run: cat README.md